### ISSUE TITLE
ExpectedVersion

### ISSUE THREAD

**Issue by gregoryyoung** [EventStore/EventStoreDB-Client-Dotnet-Legacy#30]
Writing expected version...

With expected version 0 should work if version will be 0.

**Comment by jageall** [comment]
this is covered by tests. If expected version is 0, the version after the write will be 1

test: https://github.com/EventStore/EventStoreDB-Client-Dotnet-Legacy/blob/0dc74a71115be3752d9a3859bf39b45c102c8609/test/EventStore.ClientAPIAcceptanceTests/append_to_stream.cs#L21
