### ISSUE TITLE
Append appears slow

### ISSUE THREAD

**Issue by cphillips83** [EventStore/EventStoreDB-Client-Dotnet-Legacy#37]
I actually wanted to continue the discussion on this issue here https://github.com/EventStore/EventStore/issues/1975 , while the findings were that the initial request was quite slow 1.2 seconds which should still be unacceptable, the resulting performance on subsequent appends is still unacceptable. 

I was testing the same thing as this other user and determined that, on avg, a single append to EventStore takes 8ms which is extremely slow in a append only design. I'm trying to determine where this is coming from and its a long shot from the proposed 10-20k the documents suggest you can achieve over TCP.

Are there benchmarks anywhere showing what raw through put should be considered in a single node setup with single thread vs multiple threads?

Is there a way to determine what could possibly be taking 8ms to append 50 bytes to a stream?

PC specs are fairly high end but running eventstore locally with no options passed.

**Comment by oskardudycz** [comment]
From our internal benchmarks, it appears that it should be possible to write more events than 1 per 8-20ms as you found out. Could you provide more details about your setup (disk, hosting type, etc.)?

Could you also provide information about your database version? We put a lot of performance improvements in the recent versions, so the numbers may have changed.

**Comment by cphillips83** [comment]
@oskardudycz I never moved forward with EventStore due to the performance numbers. When I created this issue the project claimed to be able to do 10-20k appends as a benchmark for performance metrics. I could never come anywhere close to this due to a single append taking 8ms which is about 125 appends per second. 

Obviously there is and was a lot of moving parts back then but I was able to get better performance with other tools which is almost assuredly related to those tools using buffered calls with a bulk fsync call sync point. I don't think EventStore had this option back then and I still don't know if it has it today (you can see some of that discussion here in this thread).
