### ISSUE TITLE
Question: Throwing exception in connection event handler

### ISSUE THREAD

**Issue by Sliverb** [EventStore/EventStoreDB-Client-Dotnet-Legacy#48]
Not sure if this is a bug or a feature request or just a plain question.

I am currently using this in a .NET core web app and configuring the event store in the ConfigureServices method in the Startup file. I register the `ErrorOccured` and `Closed` event handlers in the `IEventStoreConnection` conection. I then throw an exception for my application to catch and shutdown as I don't want the web server to run without an event store connection established.

The issue is my exceptions are caught by EventStore and handled gracefully so it never reaches my application, so startup continues. I am not sure how to signal my application (web server) to shutdown when one of these events occurs.

**To Reproduce**
```cs
IEventStoreConnection connection = EventStoreConnection.Create(
    configuration.GetConnectionString("EventStore"),
    ConnectionSettings.Create().LimitReconnectionsTo(0),
    "ESTEST"
);

connection.ErrorOccurred += (sender, args) =>
{
    throw new Exception($"Event Store Connection Failed - {args.Exception.Message}", args.Exception);
};
connection.Closed += (sender, args) =>
{
    switch (args.Reason)
    {
        case "Connection close requested by client.":
            Console.WriteLine("---------- Event Store Closed! ----------");
            break;

        case "Failed to resolve TCP end point to which to connect.":
        case "No end point to node specified.":
        case "TCP connection error occurred.":
        case "Reconnection limit reached.":
        case "Connection-wide BadRequest received. Too dangerous to continue.":
        case "No end point is specified while trying to reconnect.":
        default:
            throw new Exception($"Event Store Connection Closed - {args.Reason}");
    }
};

connection.ConnectAsync().GetAwaiter().GetResult();
```

**Expected behavior**
Exception will be thrown to the application where its caught and shuts down

**Actual behavior**
Exception is caught by EventStore and application continues w/ startup

**Logs**
```
[07,12:44:42.969,INFO] ClientAPI TcpConnection closed [12:44:42.968: N127.0.0.1:1113, L, {ef30e5ce-33e4-4566-905d-26e86376ec05}]:
[07,12:44:42.970,INFO] Received bytes: 0, Sent bytes: 0
[07,12:44:42.971,INFO] Send calls: 0, callbacks: 0
[07,12:44:42.971,INFO] Receive calls: 0, callbacks: 0
[07,12:44:42.971,INFO] Close reason: [Success] Connection establishment timeout.
[07,12:44:42.973,DEBUG] TcpPackageConnection: connection [127.0.0.1:1113, L, {ef30e5ce-33e4-4566-905d-26e86376ec05}] was closed cleanly.
[11,12:44:43.196,ERROR] Error processing EventStore.ClientAPI.Internal.TimerTickMessage
EXCEPTION(S) OCCURRED:
System.Exception: Event Store Connection Closed :: Reconnection limit reached.
   at Extensions.<>c__DisplayClass12_0.<_ConfigEventStoreEventHandlers>b__1(Object sender, ClientClosedEventArgs args) in File.cs:line 50
   at EventStore.ClientAPI.Internal.EventStoreConnectionLogicHandler.TimerTick()
   at EventStore.ClientAPI.Internal.SimpleQueuedHandler.ProcessQueue(Object state)
```

 - Operating system: Win 10

 - EventStore client version (if applicable): 5.0.5

**Comment by oskardudycz** [comment]
@Sliverb, see my answer from another issue: https://github.com/EventStore/EventStoreDB-Client-Dotnet-Legacy/issues/36#issuecomment-1007253919

> Unfortunately, that's expected behaviour, the connection is checked at the first operation call unless you're connecting to a cluster, then the connection will fail if the cluster is down. If you're using version v5 then you can enable `GossipOnSingleNode` setting and use gossip seed instead of TCP scheme, then TCP client will try to run discovery and will fail on that. From v21.10 `GossipOnSingleNode` is enabled by default.

> As .NET TCP Client is considered legacy, we won't be changing it, as it's a breaking change.
