### ISSUE TITLE
21.x embedded client

### ISSUE THREAD

**Issue by aaron-0** [EventStore/EventStoreDB-Client-Dotnet-Legacy#58]
Hi, that latest version of EventStore.Client.Embedded is 20.6.0 on nuget & yet it is mentioned in the 21.x documentation https://developers.eventstore.com/clients/dotnet/21.2/embedded.html#embeddedvnodebuilder

Is there going to be 21.x version? or is there a newer way to achieve the same thing?

Thanks

**Comment by oskardudycz** [comment]
We do not have plans at that moment to support the embedeed client. We recommend using Docker for automated tests.

Could you elaborate on why the embedded client would be helpful for you?

**Comment by aaron-0** [comment]
@oskardudycz we use event store in embedded mode in a desktop application written in .net core.
The software runs on tablets which capture data in the form of domain events written to eventstore.
Events are then synced up and down from our cloud infrastructure. 
The embedded EventStore is started and stopped as part of the net core application lifecycle, with a IHostedService that does the startup/shutdown.
Is there any way to achieve the same at present?
